<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Kuestenlogik.Bowire" Version="2.6.2" />

    <!-- Test-only -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
  </ItemGroup>
</Project>
